gpu_name = "cuda:0"
num_workers = 28

[hp]
batch_size = 1
learning_rate = 0.0001
weight_decay = 0.001
optimizer = "Adam"
network = "AlexNet"
crop_size = 399
freeze = 0.0
class_threshold = 2
aug_strength = 0.75
attention_neurons = 256
bag_size = 100
attention = "normal"
pooling = "avg"
black_threshold = 0.5
